
import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/db/mongodb';
import Notification from '@/lib/models/Notification';
import { getMongoUser } from '@/lib/auth/get-user';

export const dynamic = 'force-dynamic';

export async function GET(req: NextRequest) {
    try {
        await connectToDatabase();
        const user = await getMongoUser();
        if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

        const { searchParams } = new URL(req.url);
        const page = parseInt(searchParams.get('page') || '1');
        const limit = parseInt(searchParams.get('limit') || '20');
        const unreadOnly = searchParams.get('unread_only') === 'true';

        const query: any = { userId: user._id };
        if (unreadOnly) {
            query.read = false;
        }

        const skip = (page - 1) * limit;

        const notifications = await Notification.find(query)
            .sort('-createdAt')
            .skip(skip)
            .limit(limit)
            .lean();

        const total = await Notification.countDocuments(query);
        const unreadCount = await Notification.countDocuments({ userId: user._id, read: false });

        return NextResponse.json({
            notifications,
            pagination: {
                total,
                page,
                limit,
                pages: Math.ceil(total / limit)
            },
            unread_count: unreadCount // Useful for UI badge
        });

    } catch (error: any) {
        console.error('Error fetching notifications:', error);
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
    }
}

// Read All
export async function POST(req: NextRequest) {
    try {
        await connectToDatabase();
        const user = await getMongoUser();
        if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

        // Check path to distinguish? 
        // This is file 'route.ts' so it handles /dashboard/notifications. 
        // Read-all typically is a specific action. 
        // Users might want "read specific" too. 
        // The plan says: POST /api/v1/dashboard/notifications/read-all
        // This file is /api/v1/dashboard/notifications/route.ts
        // So this POST is strictly for creating? Dashboard notifications usually generated by system.
        // I will move Read All to `read-all` subroute to follow plan. 

        return NextResponse.json({ error: 'Method not allowed on this route. Use /read-all endpoint.' }, { status: 405 });

    } catch (error: any) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
